"""Optical-pipeline artifact dumping — FITS headers, telescope records, context snapshots.

Artifact schema reference
=========================

Context artifacts (written before processors run)
--------------------------------------------------
``task.json``
    Task dataclass fields: id, type, status, satelliteId, satelliteName,
    taskStart/Stop, assigned_filter_name, etc.  Excludes internal fields
    (locks, retry state).

``elset_cache_snapshot.json``
    Full list of TLEs available at processing time.  Each entry has
    satellite_id, name, tle (two-line array).

``observer_location.json``
    GPS/ground-station location used for TLE propagation: latitude,
    longitude, altitude, source.

``telescope_record.json``
    Telescope hardware config from the Citra API: focalLength, pixelSize,
    horizontalPixelCount, spectralConfig, etc.

``fits_header.json``
    Key FITS header fields from the captured image: DATE-OBS, CRVAL1/2,
    NAXIS1/2, XBINNING/YBINNING, EXPTIME, FILTER, SITELAT/SITELONG/SITEALT,
    INSTRUME, GAIN, TASKID, etc.

``target_satellite.json`` *(only present when satellite_data was available)*
    Full satellite record fetched from the Citra API during task execution,
    including all elsets and the ``most_recent_elset`` with the TLE that
    was actually used to point the telescope.

``pointing_report.json`` *(only present for MANUAL observation strategy)*
    Iterative slew convergence telemetry from ``point_to_lead_position()``.

Per-processor result artifacts
------------------------------
Each ``*_result.json`` contains: processor_name, confidence (0–1),
reason (human-readable), processing_time_seconds, should_upload, and
extracted_data (the processor's output dict).

``plate_solver_result.json``
    extracted_data includes: plate_solved (bool), ra_center, dec_center,
    pixel_scale (arcsec/px), field_width_deg, field_height_deg,
    wcs_image_path.

``source_extractor_result.json`` (legacy — no longer produced)
    Was generated by the now-removed SourceExtractorProcessor.

``photometry_result.json``
    extracted_data includes: zero_point, num_calibration_stars, filter.

``photometry_apass_catalog.csv``
    Raw APASS DR10 catalog stars returned for the field.

``photometry_crossmatch.csv``
    Cross-matched sources (detected + catalog).

``satellite_matcher_result.json``
    extracted_data includes: num_satellites_detected,
    satellite_observations (list of matched satellite dicts).

``satellite_matcher_debug.json``
    Comprehensive diagnostic bundle (tracking_mode, elongation_threshold,
    source_classification, predictions, match_details, reverse_match, etc.).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from astropy.io import fits

from citrasense.pipelines.common.artifact_writer import _safe_value, dump_json, task_to_dict
from citrasense.pipelines.optical.optical_processing_context import OpticalProcessingContext

if TYPE_CHECKING:
    from citrasense.pipelines.common.processing_context import ProcessingContext

logger = logging.getLogger("citrasense.OpticalArtifacts")

_FITS_HEADER_KEYS = (
    "DATE-OBS",
    "CRVAL1",
    "CRVAL2",
    "CRPIX1",
    "CRPIX2",
    "NAXIS1",
    "NAXIS2",
    "XBINNING",
    "YBINNING",
    "EXPTIME",
    "FILTER",
    "OBJECT",
    "SITELAT",
    "SITELONG",
    "SITEALT",
    "TELESCOP",
    "INSTRUME",
    "GAIN",
    "OBSERVER",
    "TASKID",
    "ORIGIN",
)


def _read_fits_header(image_path: Path) -> dict:
    """Extract diagnostic FITS header fields."""
    result: dict[str, Any] = {}
    try:
        with fits.open(image_path) as hdul:
            primary = hdul[0]
            assert isinstance(primary, fits.PrimaryHDU)
            header = primary.header
            for key in _FITS_HEADER_KEYS:
                val = header.get(key)
                if val is not None:
                    result[key] = _safe_value(val)
    except Exception as exc:
        result["_error"] = str(exc)
    return result


def dump_optical_context_artifacts(context: ProcessingContext) -> None:
    """Write pre-processing context artifacts for the optical pipeline.

    Writes: task.json, elset_cache_snapshot.json, observer_location.json,
    telescope_record.json, fits_header.json, target_satellite.json,
    pointing_report.json.
    """
    assert isinstance(context, OpticalProcessingContext)
    wd = context.working_dir
    ctx_logger = context.logger
    try:
        dump_json(wd, "task.json", task_to_dict(context.task), logger=ctx_logger)

        elsets: list[dict] = []
        if context.elset_cache:
            try:
                elsets = context.elset_cache.get_elsets()
            except Exception:
                pass
        dump_json(wd, "elset_cache_snapshot.json", elsets, logger=ctx_logger)

        location: dict[str, Any] = {}
        if context.location_service:
            try:
                location = context.location_service.get_current_location() or {}
            except Exception:
                pass
        dump_json(wd, "observer_location.json", location, logger=ctx_logger)

        dump_json(wd, "telescope_record.json", context.telescope_record or {}, logger=ctx_logger)

        dump_json(wd, "fits_header.json", _read_fits_header(context.working_image_path), logger=ctx_logger)

        if context.satellite_data:
            dump_json(wd, "target_satellite.json", context.satellite_data, logger=ctx_logger)

        if context.pointing_report:
            dump_json(wd, "pointing_report.json", context.pointing_report, logger=ctx_logger)
    except Exception as exc:
        (ctx_logger or logger).warning("Failed to dump optical context artifacts: %s", exc)
